# Generated by Django 5.2 on 2025-04-05 23:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('verification_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('verificado', models.BooleanField(default=False)),
            ],
        ),
    ]
